### ISSUE TITLE
выбираем шрифтовый логотип 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mkdocs-actionable#3]
![изображение](https://user-images.githubusercontent.com/9265326/91529646-53a18980-e912-11ea-8417-44a3d212fd44.png)

Это картинка или шрифт? @necelentano - может посмотрите?

**Comment by necelentano** [comment]
Это шрифт из Material, конкретно иконка library.

**Comment by epogrebnyak** [comment]
Может быть сделаете logo.md в корне docs (не линкуя его к структуре сайта) и выберите какие-то шрифтовые символы, которые можно использовать в качеств логотипа, штуки 3-5?

**Comment by epogrebnyak** [comment]
- [ ] линки, где сами шрифты можно посомтреть в logo.md. Немного непривычный функционал с шрифтовыми коллекциями, я как пользователь путаюсь как их подключать.

- [ ] новый логотип шрифтовой сразу прописать в mkdocs.yml, чтобы было понятно как менять (на ваш выбор какой)

**Comment by necelentano** [comment]
Добавил logo.md с некоторыми вариантами (названия иконок использовать в поиске [materialdesignicons](https://materialdesignicons.com/)). Добавил в конфиг новый логотип. Также добавил фавикон. 
p.s.
забыл прикрепить номер ишью к коммиту (

**Comment by epogrebnyak** [comment]
logo.md не могу найти может я перезаписал?

**Comment by epogrebnyak** [comment]
Может не запушили?

**Comment by necelentano** [comment]
Хм, запушил повторно.

**Comment by epogrebnyak** [comment]
Вижу, спасибо! В самом logo.md можно же вывести символы, надо плангины добавить:

https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji

![изображение](https://user-images.githubusercontent.com/9265326/91643134-49c67600-ea39-11ea-9363-5aa874c9a1ca.png)

**Comment by necelentano** [comment]
Добавил плагин, теперь иконки выводятся.

**Comment by epogrebnyak** [comment]
Попросим коллег посмотреть, высказаться какой лого берем:

https://epogrebnyak.github.io/mkdocs-actionable/logo/

**Comment by epogrebnyak** [comment]
@necelentano  - можете поменять на cube-outline логтип и favicon -  у меня быстро не получилось (

**Comment by necelentano** [comment]
Сменил логотип и фавикон на cube-outline.

**Comment by epogrebnyak** [comment]
пт, 4 сент. 2020 г., 15:29 Андрей | Andrey <notifications@github.com>:

**Comment by epogrebnyak** [comment]
![Screenshot_20200904-160101_Chrome](https://user-images.githubusercontent.com/9265326/92242233-2a5f9b00-eec8-11ea-9390-41f706201e68.jpg)

@necelentano, спасибо, будем этот вариант использовать как базовый в основном сайте.
