### ISSUE TITLE
Перевести заголовки тезисов

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mkdocs-actionable#4]
Нужен подстрочник (черновик) перевода тезисов на русский на странице 

https://github.com/epogrebnyak/mkdocs-actionable/blob/master/docs/blog/how-complex-systems-fail.md

Если какие-то тезисы будут плохо смотреться в переводе, можем оставить только ключевые, понятные.

**Comment by ghost** [comment]
[how-complex-systems-fail.zip](https://github.com/epogrebnyak/mkdocs-actionable/files/5146116/how-complex-systems-fail.zip)

**Comment by epogrebnyak** [comment]
@nataliereshetnikova - zip файл не нужен, для нас это лишний уровень упаковки. Как можно сделать: 
- дать перевод прямо здесь в ишью
- сделать коммит в репо в существующий файл, внутри комментария.

Понимаю возможно хотите осторожно сделать, но думаю в этом репо сломать особо нечего, если что - починим.

**Comment by ghost** [comment]
1.  Сложные системы по своей сути уже являются уязвимыми.
2.  Сложные системы изначально имеют несколько уровней защиты от сбоев.
3.  Катастрофа является следствием множественных сбоев, а не единоразового инцидента.
4.  Сложные системы содержат целые динамичные группы скрытых в них сбоев.
5.  Сложные системы работают в деградированном режиме, они функционируют несмотря на наличие множества недостатков.
6.  Катастрофа всегда не за горами.
7.  Поскольку отказ системы всегда является причиной нескольких факторов, попытка установить "основную первопричину" сбоя обречена на провал.
8.  Знание результата отравляет способность объективно оценить действия оператора так как кажется, что оператор "должен был знать", что определеные факторы "неизбежно" приведут к сбою.
9.  Операторы систем играют двойную роль: как управляющие и как защитники от сбоев.
10. Все действия оператора содержат в себе элемент риска.
11. Оперативные решения оператора являются следствием целого ряда производственных факторов.
12. Оператор являются адаптируемым элементом сложных систем.
13. Опыт и навыки операторов в сложных системах постоянно меняются.
14. Изменения в системах вводят новые формы сбоев.
15. Ретроспектива «причин» ограничивает эффективность защиты от будущих сбоев.
16. Безопасность - это характеристика системы, а не ee компонент.
17. Безотказная работа - это результат действий людей, которые работают над тем, чтобы система оставалась в пределах допустимой производительности.
18. Чтобы обеспечить работу без сбоев, нужен опыт работы со сбоями.

**Comment by epogrebnyak** [comment]
Перевод добавлен в комментарий: https://raw.githubusercontent.com/epogrebnyak/mkdocs-actionable/master/docs/blog/how-complex-systems-fail.md
