### ISSUE TITLE
страница 404

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mkdocs-actionable#5]
Нужна стрнациа 404, чтобы верстка не разъезжалась

Пример как сейчас:
<https://epogrebnyak.github.io/mkdocs-actionable/logo.md>

**Comment by necelentano** [comment]
если смотреть по этой [ссылке](https://epogrebnyak.github.io/mkdocs-actionable/logo/), то все хорошо.

**Comment by epogrebnyak** [comment]
вопрос не где правильная страница логотипами, вопрос, что 404 страница разъезжается 

https://epogrebnyak.github.io/mkdocs-actionable/abc

**Comment by epogrebnyak** [comment]
У меня так:

![изображение](https://user-images.githubusercontent.com/9265326/91643861-91e89700-ea3f-11ea-9071-44387cb5ed61.png)

**Comment by necelentano** [comment]
Понял.
Да, у меня также.

**Comment by epogrebnyak** [comment]
> To override the 404 error page ("file not found"), add a new template file named 404.html to the custom_theme directory. For information on what can be included in a template, review the documentation for building a custom theme.

https://www.mkdocs.org/user-guide/styling-your-docs/

**Comment by epogrebnyak** [comment]
[Здесь](https://github.com/squidfunk/mkdocs-material/issues/853) тоже обсуждают, но непонятно чей это ишью

**Comment by necelentano** [comment]
![404](https://user-images.githubusercontent.com/20335885/91644126-d2e1ab00-ea41-11ea-8770-fd5119a8e0bf.jpg)
Странно, у меня локально все работает. Может это проблема Github Pages?

**Comment by necelentano** [comment]
Да, я видел обсуждение [404 Page is not working properly](https://github.com/squidfunk/mkdocs-material/issues/853), но проблему там не решили.

**Comment by epogrebnyak** [comment]
мoжет ему полного `site_url` не хватает? или какой-то комбинации `https://epogrebnyak.github.io` + `mkdocs-actionable/`

Для github pages  сервер это `https://epogrebnyak.github.io` а сайт лежит  как бы в папке `mkdocs-actionable`

**Comment by necelentano** [comment]
да, попробуйте в конфиг файле явно прописать `site_url: https://epogrebnyak.github.io/mkdocs-actionable/`

**Comment by epogrebnyak** [comment]
Да, получилось:

![изображение](https://user-images.githubusercontent.com/9265326/91644301-4f28be00-ea43-11ea-8066-2ae6eee076f1.png)

**Comment by epogrebnyak** [comment]
Как бы не забыть при переносе v10n.com поменять

**Comment by necelentano** [comment]
Думаю, все будет хорошо)
